---
- name: Add apt key for docker
  apt_key:
    url: "{{ docker_key_url }}"
    state: present

- name: Add apt docker repo
  apt_repository:
    repo: "
    deb {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce

- name: Start and enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Get docker-compose
  get_url:
    url: "{{ docker_compose_base_url }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755

- name: Configure docker_compose
  template:
    src: docker-compose
    dest: "/{{ data_root }}/{{ env }}/docker-compose.yml"

- name: Run docker-compose
  command: docker-compose up -d
  args:
    chdir: "/{{ data_root }}/{{ env }}"
  become_user: "{{ data_owner_user }}"
